"""composite index on task_assignees user_id task_id

Revision ID: 792e10ebcd05
Revises: 215d3a10ef11
Create Date: 2026-09-10 20:22:17.057463
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '792e10ebcd05'
down_revision: str | None = '215d3a10ef11'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_assignees_user_id', table_name='task_assignees')
    op.create_index('ix_task_assignees_user_id_task_id', 'task_assignees', ['user_id', 'task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_assignees_user_id_task_id', table_name='task_assignees')
    op.create_index('ix_task_assignees_user_id', 'task_assignees', ['user_id'], unique=False)
    # ### end Alembic commands ###
